version: "3.7"

services:
#  influxdb:
#    image: bitnami/influxdb:1.8.5
#    container_name: influxdb
#    ports:
#      - "8086:8086"
#      - "8085:8088"
#    environment:
#      - INFLUXDB_ADMIN_USER_PASSWORD=bitnami123
#      - INFLUXDB_ADMIN_USER_TOKEN=admintoken123
#      - INFLUXDB_HTTP_AUTH_ENABLED=false
#      - INFLUXDB_DB=myk6db
#  grafana:
#    image: bitnami/grafana:latest
#    ports:
#      - "3000:3000"
  maria:
    image: docker.io/bitnami/mariadb:10.6
    container_name: mariadb
    ports:
      - 3307:3306
    volumes:
      - ~/docker/mariadb/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ~/docker/mariadb/var/lib/mysql:/var/lib/mysql
      - ~/docker/mariadb/var/log/maria:/var/log/maria
    environment:
      - TZ="Asia/Seoul"
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=test
      - MARIADB_USER=testuser
      - MARIADB_PASSWORD=testuser1234
  redis_container:
    # 사용할 이미지
    image: redis:latest
    # 컨테이너명
    container_name: redis_test
    # 접근 포트 설정(컨테이너 외부:컨테이너 내부)
    ports:
      - 6379:6379
    # 스토리지 마운트(볼륨) 설정
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    # 컨테이너에 docker label을 이용해서 메타데이터 추가
    labels:
      - "name=redis"
      - "mode=standalone"
    # 컨테이너 종료시 재시작 여부 설정
    restart: always
    command: redis-server /usr/local/conf/redis.conf