
spring:
  profiles:
    active: dev

# /actuator/health -> /health
management:
  endpoints:
    web:
      base-path: /

server:
  tomcat:
    threads:
      max: 200 # 생성할 수 있는 thread의 총 개수
      min-spare: 24 # 항상 활성화 되어있는(idle) thread의 개수
    max-connections: 8000 # 수립가능한 connection의 총 개수
    accept-count: 100 # 작업큐의 사이즈
    connection-timeout: 20000 # timeout 판단 기준 시간, 20
  port: 8080 # 서버를 띄울 포트번호
